version: '3.3'
services:
    bot:
        build:
          context: .
        image: kaleurbot
        restart: always
        container_name: kaleurbot
        depends_on:
           - database
        environment:
            TELEGRAM_BOT_ACCESS_TOKEN: ${TELEGRAM_BOT_ACCESS_TOKEN}
            DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
        ports:
            - 5001:80
            - 444:443
    database:
        image: mariadb:10.1
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            PMA_HOST: database
        depends_on:
           - database
        ports:
            - 8081:80